### ISSUE TITLE
An argument for 'observableOrValue' was not provided.

### ISSUE THREAD

**Issue by marcpearson** [spierala/mini-rx-store#154]
When using effect that don't require an argument ( like loadTodos() is your documentation). Typescript complain about missing argument  (observableOrValue: unknown) => void

feature-store.d.ts in line 15 =====> (observableOrValue: ObservableType | Observable<ObservableType>) => void> the argument is not optional

Angular 15
"mini-rx-store": "^4.1.0",
"mini-rx-store-ng": "^3.0.0", 
"typescript": "4.8.4",

**Comment by spierala** [comment]
Hi @marcpearson,

You can explicitly pass `void` as generic type in such cases. As you can see in this demo here: https://github.com/spierala/mini-rx-store/blob/master/apps/mini-rx-angular-demo/src/app/modules/todos/state/todos-store.service.ts#L107

**Comment by marcpearson** [comment]
Thanks for your help. I greatly appreciate it. After passing `void` my code compile again. But like you said we should not need to pass a generic if no argument for the effect

**Comment by spierala** [comment]
I will close this issue.

RxJS subject has the same behavior... it requires an explicit void as generic type.

![image](https://github.com/spierala/mini-rx-store/assets/1272446/c9adcb57-8baa-4b7e-a7f4-5463abdd0ba0)

With explicit void:

![image](https://github.com/spierala/mini-rx-store/assets/1272446/a33e39aa-f2ed-42a7-b67a-872e1e11f3c6)

Since this behavior is known from RxJS subject, I do not see it as a real issue in MiniRx effect.
