### ISSUE TITLE
Is Redux Toolkit supported?

### ISSUE THREAD

**Issue by Visual-Dawg** [spierala/mini-rx-store#200]
I discovered this really nice looking project and am thinking about switching to it for my state-management. 
However, the documentation does not use `Redux Toolkit`, but simple `Redux`.

Is this library compatible with `Redux Toolkit` or will I have to write more boilerplate for simple `Redux`?

**Comment by spierala** [comment]
Currently there is no official Redux Toolkit Support.

Which parts of Redux Toolkit would you like to use?

I tried it some time ago and e.g. `createSlice` from Redux Toolkit worked. I also saw promising results with `createEntityAdapter`. 

But honestly, I would not recommend to use Redux Toolkit with MiniRx. Some parts of Redux Toolkit might work (with some luck), but it would be a too huge task for MiniRx to be fully compatible.

MiniRx has support for [ts-action](https://github.com/cartant/ts-action) which reduces boilerplate already a lot: https://mini-rx.io/docs/ts-action

You can also look into MiniRx [FeatureStore](https://mini-rx.io/docs/fs-quick-start) / [ComponentStore](https://mini-rx.io/docs/component-store): no boilerplate at all :)

**Comment by Visual-Dawg** [comment]
@spierala Hey, thank you for the quick reply :) 
Yes, I am thinking about `reducer`s and `createSlice`, but `ts-action` with the `immer` flavour seems to be just as good :)

**Comment by spierala** [comment]
Ahhh, you are using Svelte! nice!

Svelte Stores are for sure good for simple state management.

Did you see the MiniRx Svelte Demo? https://github.com/spierala/mini-rx-svelte-demo
Demo in action: https://svelte-demo.mini-rx.io/

**Comment by Visual-Dawg** [comment]
Yes, I saw it (and discovered the library through that too :D )

Im nearly done with setting up my state with `mini-rx`, but I am seeing that the typings of `mini-rx` `configureStore` are not inferred, as with `redux-toolkit`s solution.

Especially things like `AppState`, would benefit from that I believe.

**Comment by spierala** [comment]
Yes, MiniRx configureStore does not infer typing from reducers. It would be difficult to implement as well because in MiniRx you can add reducers dynamically later.

IMO the store does not necessarily need to know about the state interface.
It could be beneficial when trying to select state directly from the store.

But when using Redux you should better use memoized selectors anyways. Which makes selecting state from the global state object easier.  Also these selectors are better composable and reduce the amount of calculations. See here the docs for memoized selectors:

https://mini-rx.io/docs/selectors#memoized-selectors

`createFeatureStateSelector` takes a generic type which represents the interface of the feature/slice. 
You use the same interface for the reducer and for `createFeatureStateSelector`.
That should provide enough typing for selecting state.

**Comment by Visual-Dawg** [comment]
I see, thank you :)
