### ISSUE TITLE
Improve ID generation

### ISSUE THREAD

**Issue by spierala** [spierala/mini-rx-store#224]
The id generation could be improved. 

Theoretically Math.random can return 0, which causes an exception.

Maybe the nano id implementation is not so bad: https://github.com/ai/nanoid/blob/main/non-secure/index.js#L23-L32

I could imagine to also use shorter ids. Now the length is 10 or 11. 

IDs with a length of 6-8 should be good enough.

_Originally posted by @spierala in https://github.com/spierala/mini-rx-store/pull/211#discussion_r1864996708_

**Comment by carlos-ds** [comment]
Hi @spierala I can have a look at this if you want :smiley: 
Just looked up Nano ID and that looks sufficient indeed. There's even a [tool to calculate the collision probability](https://zelark.github.io/nano-id-cc/). It states:
- For 6 characters: _37K IDs needed, in order to have a 1% probability of at least one collision_.
- For 8 characters: _2M IDs needed, in order to have a 1% probability of at least one collision_.

So I feel 6 characters should be sufficient for this use case?

**Comment by spierala** [comment]
@carlos-ds yes! that would be great!

A really cool tool! I was googling for probabilities... but that tool is so much better than googling :)

6 chars it is!

**Comment by spierala** [comment]
You can branch from release-2024.1

**Comment by spierala** [comment]
Indeed that's the plan. Copy paste only the necessary pieces, adjust, add license to the code and update the LICENSE file.

And a small test would be great 😀
